
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9094
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              org.springframework.cloud.gateway.route.RouteDefinition: info


