
 spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
## product server route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
## Order service route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
## Inventory service route
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
## Discovery server route
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
## Discovery server route for static
        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9999
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              org.springframework.cloud.gateway.route.RouteDefinition: info

