
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/new-microservice
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 9093